import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.css'
import NavBarComponent from './Components/NavBarComponent'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      
      <body>
        <NavBarComponent/>
        {children}
        <footer className='text-center bg-secondary dysplay-4 text-white'>Derechos Reservados</footer>
      </body>
       
    </html>
  )
}
